### ISSUE TITLE
suggested feature

### ISSUE THREAD

**Issue by ivanovSPvirtru** [MattBoatman/i18next-pseudo#1]
Netflix suggested that we should wrap all strings in to brackets (like this `[ḀḀḀḅṓṓṓṵṵṵṭ]`), so we could explicitly see where any string ends, and check if this string fits. Without brackets, it can be unclear where any string ends.

**Comment by IvanovSP** [comment]
Done. That's my home account ).

**Comment by MattBoatman** [comment]
https://github.com/MattBoatman/i18next-pseudo/pull/2
